### ISSUE TITLE
Document API Endpoints

### ISSUE THREAD

**Issue by jonatangroncode** [jonatangroncode/GruppProjekt#20]

**Comment by jonatangroncode** [comment]
Skapa dokumentation för API:et (t.ex. med Swagger eller Postman).

- [ ] Beskriv alla endpoints och deras användning
- [ ] Dokumentera exempelanrop

**Comment by Natti94** [comment]
Skapat API endpoint för user, återkoppla om vi ska endpoints för andra models.
